version: '3'

services:
  # workspace container
  workspace:
    build:
      context: ./workspace
    working_dir: /app
    volumes:
      - ./laravel:/app
    privileged: true
    stdin_open: true
    tty: true

  # php-fpm
  app:
    build:
      context: ./
      dockerfile: phpfpm/Dockerfile
    depends_on:
      - workspace
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www

  # nginx
  web:
    build:
      context: ./nginx
    working_dir: /var/www
    depends_on: 
      - app
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
